### ISSUE TITLE
Support deep link redirect in web3-react

### ISSUE THREAD

**Issue by Lbqds** [alephium/alephium-web3#280]
Based on the discussion of [this issue](https://github.com/alephium/alephium-frontend/issues/55), we need to:

1. Upgrade walletconnect to the latest version
2. Store the deep link in web3-react

**Comment by nop33** [comment]
Thank you for this issue @Lbqds! 🙏 

Shouldn't there be one more subtask, something like:

3. Redirect to deep link on session requests

?

**Comment by Lbqds** [comment]
> Thank you for this issue @Lbqds! 🙏
> 
> Shouldn't there be one more subtask, something like:
> 
> 3. Redirect to deep link on session requests
> 
> ?

I think the WalletConnect sign-client has already done this: https://github.com/WalletConnect/walletconnect-monorepo/blob/23f2f55eef85d6fdad76dee9e8acab3948512082/packages/sign-client/src/controllers/engine.ts#L375, each time the dApp sends a request, the sign-client will redirect to the deep link. And I'll do some tests when I start working on this.
