### ISSUE TITLE
Skip recompilation by default for mainnet and testnet deployment

### ISSUE THREAD

**Issue by polarker** [alephium/alephium-web3#343]

**Comment by Lbqds** [comment]
When deploying, we only recompile if one of the following conditions is met:

1. There are changes in the source code.
2. There are changes in compiler options.
3. There are changes in the full node version.

If there are changes in the source code but the user forgot to recompile, we prompt the user that the contract has changed and ask for confirmation if they want to redeploy the contracts.

If we want to skip recompilation, does this mean we need to skip these checks?
