### ISSUE TITLE
Using @alephium/web3-wallet in react-native fails

### ISSUE THREAD

**Issue by gilles-hemmerle** [alephium/alephium-web3#362]
## Context

I'm currently trying to implement the  bridge in sezame wallet (react native application).
I imported wormhole-sdk and I try to use the bridge directly through the wallet.

I need to use `transferLocalTokenFromAlph` which expects a SignerProvider as a first params. So I figured out in your documentation that we can create a SignerProvider from the `PrivateKeyWallet` class which is exposed in the `@alephium/web3-wallet project`.

## Environnement 

- node 18.19.0
- yarn 1.22.21

**What I did**

I imported the following dependencies :

```json
    "@alephium/web3": "^0.42.0",
    "@alephium/web3-wallet": "^0.42.0",
    "@alephium/wormhole-sdk": "^0.2.5",
```

However, when I want to import the PrivateKeyWallet like this :

`import {PrivateKeyWallet} from '@alephium/web3-wallet';`

 I get the following error when running the app in a ios device

`npx react-native start --reset-cache` and then executing the app : `yarn ios`

error: Error: While trying to resolve module `@alephium/web3-wallet` from file `sezame/wallet-react-native/src/screens/bridge/bridge-screen.tsx`, the package `sezame/wallet-react-native/node_modules/@alephium/web3-wallet/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`sezame/wallet-react-native/node_modules/@alephium/web3-wallet/dist/alephium-web3.min.js`. Indeed, none of these files exist:

![image](https://github.com/alephium/alephium-web3/assets/2291800/b783862f-ba0b-4d8c-8fa0-2739fe0ac173)

## Repo to desmonstrate the issue

https://github.com/gilles-hemmerle/alephium-web3-wallet-issue

## Questions

* Anyone does have the same issue?
* Did you already try to implement the bridge in your rect native wallets, if yes, do you have a git showing this?
* I'm using the womhole sdk `transferLocalTokenFromAlph` function. The first argument requires a `SignerProvider`. But if I pass a `PrivateKeyWallet`, it complains : 'PrivateKeyWallet' is not assignable to the 'SignerProvider' type parameter. Howver,  in the source files I see `class PrivateKeyWallet extends SignerProviderSimple` and `abstract class SignerProviderSimple extends SignerProvide`, so `transferLocalTokenFromAlph` should accept a `PrivateKeyWallet`, do I have some inompatibility between the dependencies i'm using?

**Comment by nop33** [comment]
@gilles-hemmerle maybe having a look at our own React Native mobile wallet will give you some help? https://github.com/alephium/alephium-frontend/tree/next/apps/mobile-wallet

**Comment by nop33** [comment]
It might be that the [entry points](https://github.com/alephium/alephium-web3/blob/master/packages/web3-wallet/package.json#L10-L15) of the `@alephium/web3-wallet` package need to be changed to match [the ones](https://github.com/alephium/alephium-web3/blob/master/packages/web3/package.json#L6-L12) in the `@alephium/web3` package.

**Comment by nop33** [comment]
To validate this hypothesis, I would suggest @gilles-hemmerle to find the `package.json` file inside the `node_modules` folder of their React Native project and change the entry points to be:

```json
  "main": "dist/src/index.js",
  "browser": "dist/alephium-web3-wallet.min.js",
  "exports": {
    "node": "./dist/src/index.js",
    "default": "./dist/alephium-web3-wallet.min.js"
  },
```

and then launch the React Native dev server again and see if the issue persists.

**Comment by polarker** [comment]
@nop33 The changes you introduced work well with our mobile wallet, right?

**Comment by nop33** [comment]
I was waiting for a new web3 version to be released on npm, I havent' had the chance to update yet. Will do it later today

**Comment by polarker** [comment]
> I was waiting for a new web3 version to be released on npm, I havent' had the chance to update yet. Will do it later today. But based on my tests here, it works: [#352 (comment)](https://github.com/alephium/alephium-web3/pull/352#issue-2303001306)

We have released `0.42.0` today. Please help us give it a test!

**Comment by mvaivre** [comment]
Successfully tested 0.42.0 on mobile and explorer: https://github.com/alephium/alephium-frontend/pull/619 
As expected, this allowed us to remove node polyfilling from the explorer.
Will test more with our other Apps, but so far so good ;)

**Comment by gilles-hemmerle** [comment]
> @gilles-hemmerle maybe having a look at our own React Native mobile wallet will give you some help? https://github.com/alephium/alephium-frontend/tree/next/apps/mobile-wallet

Thanks, did you integrate the bridge in your wallet actually?

**Comment by gilles-hemmerle** [comment]
> Successfully tested 0.42.0 on mobile and explorer: [alephium/alephium-frontend#619](https://github.com/alephium/alephium-frontend/pull/619) As expected, this allowed us to remove node polyfilling from the explorer. Will test more with our other Apps, but so far so good ;)

This minimal repo is working in your end? Can I ask you which node / npm / yarn version you are using?
https://github.com/gilles-hemmerle/alephium-web3-wallet-issue

**Comment by polarker** [comment]
@gilles-hemmerle We will test the bridge SDK tomorrow. That one might need to be updated to support `react-native`

**Comment by gilles-hemmerle** [comment]
Have you been able to test ?

I'm still strugling using PrivateKeyWallet in a react native app.
And, as your bridge sdk required a valid signer, I am unable to integrate the bridge in the wallet.

Plus I tried to check in your mono repo wallet, and it appears you are not using PrivateKeyWallet to create a signer from a private key (which seems the only way I could see to use the existing bridge sdk).

I wanted to finalize the bridge implementation before the event this weekend but I'm strugling to implement the sdk in a react native app.

**Comment by polarker** [comment]
Hey @gilles-hemmerle , thanks for the ping. Sorry that I have forgotten this. Let me do it right now.

**Comment by nop33** [comment]
@gilles-hemmerle 1.0.3 should be addressing the issue you had with @alephium/web3-wallet. However, we are facing another known issue now: https://github.com/alephium/alephium-frontend/issues/683

**Comment by nop33** [comment]
@gilles-hemmerle can you check of `1.0.5` works for you too?

**Comment by gilles-hemmerle** [comment]
Yes seems to work, I'm now able to create a PrivateKeyWallet successfully, thanks!
