### ISSUE TITLE
`binary-parser` is problematic when used in browser environments with strict CSP

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-web3#398]
## Problem

The [`binary-parser`](https://www.npmjs.com/package/binary-parser) dependency of `@alephium/web3` seems unsafe because it allows for JS eval.

When a frontend application has a strict Content Security Policy that does not allow `unsafe-eval`, the `isValidAddress` will return `false` for multi-sig addresses because decoding fails with this error:

https://github.com/alephium/alephium-web3/blob/master/packages/web3/src/address/address.ts#L66

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".
```

We discovered that the source of the problem are these lines of `binary-parser`:

https://github.com/keichi/binary-parser/blob/d0332454adff5ded936ce87f0397de11b1fd0709/lib/binary_parser.ts#L839-L847

```ts
  compile() {
    const importPath = "imports";
    const ctx = this.getContext(importPath);
    this.compiled = new Function(
      importPath,
      "TextDecoder",
      `return function (buffer, constructorFn) { ${ctx.code} };`
    )(ctx.imports, TextDecoder);
  }
```

## Notes
If we want to use the tx decoder from the web3 package in the wallets to avoid calling the tx decoding endpoint, we will suffer from the same problem.

I looked for [alternatives](https://github.com/dloss/binary-parsing) but didn't find many.

## Possibly related
- https://github.com/keichi/binary-parser/issues/258 (issue that I just created)
- https://github.com/keichi/binary-parser/pull/143/files
- https://github.com/keichi/binary-parser/issues/142

**Comment by polarker** [comment]
This has been resolved now
